In [0]:
import numpy as np


In [0]:
a = [1,2,3,4,5,6,7,8,9,10]


In [0]:
a = np.random.rand(10,1)

SyntaxError: ignored

(10, 1)

In [0]:
a.reshape(10,1)

array([[0.76089798],
       [0.23203315],
       [0.84524161],
       [0.09131517],
       [0.88864119],
       [0.99941344],
       [0.38938867],
       [0.79384303],
       [0.15949185],
       [0.58007071]])

In [0]:
a.dtype

dtype('float64')

In [0]:
a.ndim

2

In [0]:
np.mean(a)

0.5740336811928719

In [0]:
b = np.random.rand(20,1)

In [0]:
np.var(b)

0.12406731010933456

In [0]:
np.std(b)

0.35223189819965844

In [0]:
A = np.random.rand(10,20)

In [0]:
B = np.random.rand(20,25)

In [0]:
np.matmul(A,B)

array([[5.65585783, 4.51165196, 5.69723705, 6.04516875, 6.04200699,
        4.78721552, 4.71691563, 5.11967449, 5.5163758 , 4.9194771 ,
        3.5505923 , 4.89324104, 4.73059625, 4.93867485, 4.46319763,
        4.37107746, 4.87350939, 5.66513739, 4.3348761 , 5.71883764,
        5.2926906 , 4.42905345, 4.8332076 , 4.24717122, 5.31011064],
       [4.74182039, 3.94751238, 4.41068586, 6.09172917, 5.44466575,
        3.83724753, 3.66079421, 4.10807271, 4.93047813, 4.03822647,
        4.05096479, 4.75050214, 3.70449008, 3.89133727, 3.16454513,
        4.69411436, 4.1019645 , 4.92087853, 3.9598811 , 4.12789518,
        4.54052134, 4.85944815, 4.14482398, 3.07232508, 4.78386279],
       [4.83332143, 4.16207367, 4.6511385 , 5.9656251 , 5.19209549,
        4.09893651, 3.95031771, 4.17037257, 4.86293966, 4.5006149 ,
        3.953017  , 4.50851054, 4.01851377, 4.09487557, 2.94624675,
        4.65561965, 3.93936475, 5.03018324, 3.66763453, 4.40926464,
        4.9558964 , 4.75472304, 3.84406604, 3.

In [0]:
c = np.matmul(A,B)

In [0]:
c.reshape(10,25)

array([[5.65585783, 4.51165196, 5.69723705, 6.04516875, 6.04200699,
        4.78721552, 4.71691563, 5.11967449, 5.5163758 , 4.9194771 ,
        3.5505923 , 4.89324104, 4.73059625, 4.93867485, 4.46319763,
        4.37107746, 4.87350939, 5.66513739, 4.3348761 , 5.71883764,
        5.2926906 , 4.42905345, 4.8332076 , 4.24717122, 5.31011064],
       [4.74182039, 3.94751238, 4.41068586, 6.09172917, 5.44466575,
        3.83724753, 3.66079421, 4.10807271, 4.93047813, 4.03822647,
        4.05096479, 4.75050214, 3.70449008, 3.89133727, 3.16454513,
        4.69411436, 4.1019645 , 4.92087853, 3.9598811 , 4.12789518,
        4.54052134, 4.85944815, 4.14482398, 3.07232508, 4.78386279],
       [4.83332143, 4.16207367, 4.6511385 , 5.9656251 , 5.19209549,
        4.09893651, 3.95031771, 4.17037257, 4.86293966, 4.5006149 ,
        3.953017  , 4.50851054, 4.01851377, 4.09487557, 2.94624675,
        4.65561965, 3.93936475, 5.03018324, 3.66763453, 4.40926464,
        4.9558964 , 4.75472304, 3.84406604, 3.

In [0]:
np.sum(c)

1228.9676053905243