In [0]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline
from sklearn import datasets
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [0]:
data = datasets.load_digits()

In [0]:

X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=42)

In [4]:
svclassifier = SVC(kernel='linear', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pred1 = svclassifier.predict(X_test)
print("When kernel = 'linear'\n")
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred1))
print("\n\nClassification Report:\n", classification_report(y_test, y_pred1))

When kernel = 'linear'

Confusion Matrix:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  1]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  1  0  0  1  0 37]]


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.97      1.00      0.98        28
           2       1.00      1.00      1.00        33
           3       0.97      0.94      0.96        34
           4       0.98      0.98      0.98        46
           5       0.96      1.00      0.98        47
           6       1.00      1.00      1.00        35
           7       0.97      0.97      0.97        34
           8       1.00      0.97      0.98        30
           9       0.95      0.93      0.94        40

   m

In [5]:
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pred2 = svclassifier.predict(X_test)
print("When kernel = 'poly'\n")
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred2))
print("\n\nClassification Report:\n", classification_report(y_test, y_pred2))

When kernel = 'poly'

Confusion Matrix:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  1  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  2  0  0  0  0  0  0 27  1]
 [ 0  0  0  1  1  0  0  0  0 38]]


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.93      0.96      0.95        28
           2       1.00      1.00      1.00        33
           3       0.97      0.97      0.97        34
           4       0.98      1.00      0.99        46
           5       0.98      0.98      0.98        47
           6       0.97      1.00      0.99        35
           7       1.00      0.97      0.99        34
           8       0.96      0.90      0.93        30
           9       0.95      0.95      0.95        40

   mic

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:
svclassifier = SVC(kernel='rbf', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pred3 = svclassifier.predict(X_test)
print("When kernel = 'rbf'\n")
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred3))
print("\n\nClassification Report:\n", classification_report(y_test, y_pred3))

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


When kernel = 'rbf'

Confusion Matrix:
 [[14  0  0 19  0  0  0  0  0  0]
 [ 0 20  0  8  0  0  0  0  0  0]
 [ 0  0 16 17  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  0 33 13  0  0  0  0  0]
 [ 0  0  0 44  0  3  0  0  0  0]
 [ 0  0  0  9  0  0 26  0  0  0]
 [ 0  0  0 15  0  0  0 19  0  0]
 [ 0  0  0 16  0  0  0  0 14  0]
 [ 0  0  0 31  0  0  0  0  0  9]]


Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.42      0.60        33
           1       1.00      0.71      0.83        28
           2       1.00      0.48      0.65        33
           3       0.15      1.00      0.26        34
           4       1.00      0.28      0.44        46
           5       1.00      0.06      0.12        47
           6       1.00      0.74      0.85        35
           7       1.00      0.56      0.72        34
           8       1.00      0.47      0.64        30
           9       1.00      0.23      0.37        40

   micr

In [7]:
svclassifier = SVC(kernel='sigmoid', degree=8)  
svclassifier.fit(X_train, y_train) 
y_pred4 = svclassifier.predict(X_test)
print("When kernel = 'sigmoid'\n")
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred4))
print("\n\nClassification Report:\n", classification_report(y_test, y_pred4))

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


When kernel = 'sigmoid'

Confusion Matrix:
 [[ 0 33  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0 33  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0 46  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  0  0]
 [ 0 35  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]]


Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        33
           1       0.08      1.00      0.14        28
           2       0.00      0.00      0.00        33
           3       0.00      0.00      0.00        34
           4       0.00      0.00      0.00        46
           5       0.00      0.00      0.00        47
           6       0.00      0.00      0.00        35
           7       0.00      0.00      0.00        34
           8       0.00      0.00      0.00        30
           9       0.00      0.00      0.00        40

   

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
